config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'
	
	get 'about', to: 'pages#about'
	resources :goals
	
	get 'signup', to: 'users#new'
	resources :users, except:[:new]
	
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'
	
	resources :categories, except: [:destroy]
	

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :goal_categories
	has_many :goals, through: :goal_categories
	
	validates :name, presence: true, length: { minimum: 3, maximum: 10 }
	validates_uniqueness_of :name
	
end

app/models/goal.rb
class Goal < ActiveRecord::Base
	belongs_to :user
	has_many :goal_categories
	has_many :categories, through: :goal_categories
	
	
	#Add validation when creating goals
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/models/goal_category.rb
class GoalCategory < ActiveRecord::Base
	belongs_to :goal
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
	#Defining 1:many association
	#Whatever goals the user has, it will destroy them if they are deleted
	has_many :goals, dependent: :destroy
	#before the user accesses the database, it will save the email address in lowercase before saving it in the db
	before_save { self.email = email.downcase }
	#Validate username
	validates :username, presence: true,
						uniqueness: { case_sensitive: false }, 
						length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
						length: { maximum: 50 },
						uniqueness: { case_sensitive: false },
	#Check email format
						format: { with: VALID_EMAIL_REGEX }
	#Method for password authentication
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	#New login methods; available to controllers but not views by default
	helper_method :current_user, :logged_in?
	
	def current_user
		#return current useruser else if not, then return this user object if user_id session in db exists
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	
	def logged_in?
		#convert to boolean
		!!current_user
	end
	
	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to root_path
		end
	end
	
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:index, :show]
	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end
	
	def new
		@category = Category.new
	end
	
	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category was created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end
	
	def edit
		@category = Category.find(params[:id])
	end
	
	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success] = "Category was successfully updated"
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end
	
	def show
		@category = Category.find(params[:id])
		@category_goals = @category.goals.paginate(page:params[:page], per_page: 5)
	end
	
	private
	def category_params
		params.require(:category).permit(:name)
	end
	
	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?) 
			flash[:danger] = "Only admins can perform that action"
			redirect_to categories_path
		end
	end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	#Ensure the set_goal method is called before the other methods are actioned
	before_action :set_goal, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		#Display 5 items per page using pagination
		@goals = Goal.paginate(page: params[:page], per_page: 5)
	end
	
	def new
		@goal = Goal.new
	end
	
	def edit
		#find the goal based on its id
	end
	
	def create
		#Using gemfile called 'byebug'
#debugger 
		#Display what has been passed in into the controller
		#
#		render plain: params[:goal].inspect
		#Create an instance variable with method
		@goal = Goal.new(goal_params)
		#the creator of the goal will be associated as the current user
		@goal.user = current_user
		if @goal.save
			#do something
			flash[:success] = "You have created a new goal!"
			redirect_to goal_path(@goal)
		else
			#do something else
			render 'new'
		end
	end

	def update
		#Perform validations
		if @goal.update(goal_params)
			flash[:success] = "Goal was successfully updated"
			#redirect to goal show page
			redirect_to goal_path(@goal)
		else
			render 'edit'
		end
	end
		
	def show
	end

	def destroy

		@goal.destroy
		flash[:danger] = "Goal was deleted"
		redirect_to goals_path
	end
	
	private
	
	def set_goal
		@goal = Goal.find(params[:id])
	end
	
	#define the method
	def goal_params
		params.require(:goal).permit(:title, :description, category_ids:[])
	end
	
	def require_same_user
		if current_user != @goal.user and !current_user.admin?
			flash[:danger] = "You can only edit or delete your own goal"
			redirect_to root_path
		end
	end
	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	#Define a method
	def home
		redirect_to goals_path if logged_in?
	end
	
	def about
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end
	
	#handles form submissions
	def create
		user = User.find_by(email: params[:session][:email].downcase)
		#user is found & based on password is true then...
		if user && user.authenticate(params[:session][:password])
			#browser cookies saves user_id and used for requests
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to user_path(user)
		else
			#flash message once
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end
	
	#stops user session
	def destroy
		session[:user_id] = nil
		flash[:success]= "You have logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	#before action ensure that the @user variable is ready for the edit, update & show actions
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	#Restricted for admin users!
	before_action :require_admin, only:[:destroy]
	
	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end
	
	def edit
		
	end
	
	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to goals_path
		else
			render 'edit'
		end
	end
	
	def show
		@user_goals = @user.goals.paginate(page: params[:page], per_page: 5)
	end
	
	#FOR ADMIN USERS ONLY!
	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all goals have been deleted"
		redirect_to users_path
	end
	
	private
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end
		
		#Define method
		def set_user
		@user = User.find(params[:id])
		end
		
		def require_same_user
			if current_user != @user and !current_user.admin?
				flash[:danger] = "You can only edit your own account"
				redirect_to root_path
			end
		end
	
		#Prevent non-admin users deleting goals
		def require_admin
				if logged_in? and !current_user.admin?
					flash[:danger] = "Only admin users can perform that action"
					redirect_to root_path
				end
		end

	end

app/helpers/application_helper.rb
module ApplicationHelper
	#pass in the user object
	#Documentation on Gravatar: https://en.gravatar.com/support/
	#Gravatar urls are based on MD5 hash of the user's email
	#Ruby uses 'hexdigest' method - http://ruby-doc.org/stdlib-1.9.3/libdoc/digest/rdoc/Digest/Class.html
	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/categories/_category.html.erb
	<span class="badge">
		<%= link_to category.name, category_path(category) %> &nbsp;
	</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj:@category %>

<!--Display form-->
<%= form_for(@category, :html => {class: "form-horizontal",role: "form"}) do |x| %>
		
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= x.label :name %>
			</div>
				<div class="col-sm-8">
					<%= x.text_field :name, class: "form-control", placeholder: "Category name", autofocus:true %>
				</div>
		</div>
		
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
<!--If a new user is signing up, show this "Sign up" message else..-->
				<%= x.submit class: "btn btn-primary btn-lg" %>
			</div>
		</div>
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to 'Cancel request and return to view goals', goals_path %> ]	
		</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category</h1>


<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<div align="center">
	<%= will_paginate %>
	<% @categories.each do |category| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li class="goal-title">
						<%= link_to "#{category.name}", category_path(category) %>
					</li>
					<li>
<!--Display the current number of individual goals created by users in the app-->
						<small><%= pluralize(category.goals.count, "goal") %></small>
					</li>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
	<div align="center">
		<% if logged_in? and current_user.admin? %>
			<div class="row">
				<span class="badge"><%= link_to "Edit Category name", edit_category_path(@category) %></span>
			</div>
		<% end %>
		<%= will_paginate @category_goals %>
	</div>
<%= render 'goals/goal', obj: @category_goals %>
<div align="center">
	<%= will_paginate @category_goals%>
</div>

app/views/goals/_form.html.erb
<%= render 'shared/errors', obj: @goal %>

<div class='row'>
	<div class='col-xs-12'>
	<!--Display the form-->
	<%= form_for(@goal, :html => {class:"form-horizontal", role:"form"}) do |x| %>

	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= x.label :title %>
		</div>
		
		<div class="col-sm-8">
			<%= x.text_field :title, class: "form-control", placeholder: "Title of Goal", autofocus: true %>
		</div>
	</div>

	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= x.label :description %>
		</div>
		<div class="col-sm-8">
			<%= x.text_area :description, rows: 10, class: "form-control", placeholder: "Describe your goal" %>
		</div>
	</div>
<!--Display each category title-->
	<div class="form-group">
		<div class="row">
			<div class="col-sm-offset-2 col-sm-8">
				<%= x.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
				<% cb.label(class:"checkbox-inline input_checkbox"){cb.check_box(class:"checkbox") + cb.text} %>
				<% end %>
			</div>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= x.submit class: 'btn btn-primary btn-lg' %>
		</div>
	</div>
			<% end %>

		 <div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Cancel request and return to listing goals", goals_path %> ]
		</div>
	</div>
</div>

app/views/goals/_goal.html.erb
<!--Iterate through each goal created by user-->
	<% obj.each do |goal| %>

<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="goal-title">
<!--Make the goal title to be a link and go to that goal page-->
				<%= link_to goal.title, goal_path(goal) %>
			</div>
			
			<div class="goal-body">
<!--Use a truncate method-->
				<%= truncate(goal.description, length: 100) %>
				<div class="goal-meta-details">
				<small>
<!--display if true-->
					Created by: <%= goal.user.username if goal.user %>,
					<%= time_ago_in_words(goal.created_at) %> ago,
					last updated: <%= time_ago_in_words(goal.updated_at) %>
					</small>
				</div>
			</div>
			
				<% if goal.categories.any? %>
					<p>Categories: <%= render goal.categories %></p>
				<%end%>
			
			<% if logged_in? && (current_user == goal.user || current_user.admin?) %>
				<div class="goal-actions">
					<%= link_to 'Edit this goal', edit_goal_path(goal), class: "btn btn-xs btn-primary" %> 
					<%= link_to 'Delete this goal', goal_path(goal), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
				</div>
			<% end %>
			</div>
		</div>
	</div>
	<% end %>

app/views/goals/edit.html.erb
<h1 align="center">Edit existing Goal</h1>
<!--refactored form into partial-->
<%= render 'form' %>

app/views/goals/index.html.erb
<h1 align="center">Listing all Goals</h1>
<!--Add display for pagination-->
<div align="center">
	<%= will_paginate %>
</div>

<%= render 'goal', obj: @goals %>

<div align="center">
	<%= will_paginate %>
</div>

app/views/goals/new.html.erb
<h1 align="center">Your Goal</h1>
<!--refactored form into partial-->
<%= render 'form'%>

app/views/goals/show.html.erb
<h2 align="center">Title:<%= @goal.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
<!--If goal has a user then...-->
	<% if @goal.user %>
		<ul class="listing">
			<div class="row center">
				<div class="col-md-4 col-md-offset-4">

				<li>Created by:</li>

					<li>
		<!--link goes to that user's showpage-->
						<%= link_to gravatar_for(@goal.user), user_path(@goal.user) %>
					</li>
					<li class="goal-title">
						<%= link_to @goal.user.username, user_path(@goal.user) %>
					</li>
					<li>
		<!--display the no. of goals the user has created if the user has any-->
						<small>
							<%= pluralize(@goal.user.goals.count, "goal") if @goal.user.goals %>
						</small>
					</li>
				</div>
			</div>
		</ul>
	<% end %>
	
	<h4 class="center description">
		<strong>Description:</strong>
	</h4>
	<hr>
<!--Go through each of the the categories and display them-->
	<%= simple_format(@goal.description) %>
	<% if @goal.categories.any? %>
		<p>Categories:</p>
	<% end %>
	
	<div class="goal-actions">
		<% if logged_in? && (current_user == @goal.user || current_user.admin?) %>
						<%= link_to 'Edit this goal', edit_goal_path(@goal), class: "btn btn-xs btn-primary" %> 
		<%= link_to 'Delete this goal', goal_path(@goal), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" %>
		<% end %>
				<%= link_to 'View all goals', goals_path, class: "btn btn-xs btn-success" %>
		</div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy;
			<a href="http://www.strongpoint.io">Strongpoint Studios</a> by 
			<a href="http://github.com/vtt01uk">vtt01uk</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path%></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<!--Styling this partial-->
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
<!--Displays the appropriate danger, alert or success messages-->
		<div class='alert alert-<%="#{name}" %>'>
<!--Display the bang symbol if the message is danger-->
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<%= link_to "commit2it", root_path, class:"navbar-brand", id:"logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><%= link_to "Goals", goals_path %></li>
				<li><%= link_to "Users", users_path %></li>
				<% if logged_in? %>
				 <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions<span class="caret"></span></a>
          <ul class="dropdown-menu">
						<li><%= link_to "New Goal", new_goal_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
				<% end %>
			 <li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><%= link_to "All categories", categories_path %></li>
						<% Category.all.each do | category| %>
						<li><%= link_to "#{category.name}", category_path(category) %></li>
						<% end %>
						<% if logged_in? and current_user.admin? %>
							<li role="separator" class="divider"></li>
						<% end %>
						<li><%= link_to "Create New Category", new_category_path %></li>
					</ul>
				</li>
      </ul>
      
       <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
				<% if logged_in? %>
				 <li><%= link_to 'Log out', logout_path, method: :delete %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your profile<%= "Admin" if current_user.admin? %><span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><%= link_to "Edit profile", edit_user_path(current_user)%></li>
							<li><%= link_to "View profile", user_path(current_user)%></li>

							<li><a href="#">Something else here</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>
					</li>
				<% else %>
					 <li><%= link_to 'Log in', login_path %></li>
					 <li><%= link_to 'Sign up', signup_path %></li>
				<% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Commit2it | Be a Better You</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
<!--refactored messages into partial-->
	<%= render 'layouts/messages' %>	
	<div class="container">
<!--All views get served in this 'yield'-->
		<%= yield %>
<!--Footer-->
	</div>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<h1>
	<a href="https://github.com/vtt01uk/Commit2it#README">About this Project</a>
	</h1>
	<div class="container">
	<h4><i>Be a better you</i></h4>
		<p>
	Welcome to Commit2it; a blog-site where like-minded people share their goals and gain advice, tips & tricks from others who have been on similar journeys or similar paths.
		</p>
		<p>
	Whether it be losing weight, running a marathon, getting a job at a particular company or helping others at a shelter home, at Commit2it, you will find others just like you.
		</p>
		<p>
	You are not alone in your quest to be better, do better or feel better so let's help each other achieve amazing results!
		</p>

<!--			<%= link_to 'Home', root_path %>-->
	</div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
	<h1>COMMIT 2 IT</h1>

	<%= link_to "Come join us", signup_path, class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/pages/index.html.erb
<h1>This is the Homepage</h1>
<%= link_to 'About', pages_about_path%>

app/views/shared/_errors.html.erb
<!--Display validation messages-->
<% if obj.errors.any? %>
<!--Style the validation errors-->
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
<!--Use pluralize method to give the number of errors occured and display error or errors-->
					<%= pluralize(obj.errors.count, "error") %> prohibited this goal from being created: 
					</h2>
					<div class="panel-body">
						<ul>
							<% obj.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
								<% end %>								
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>

<!--Display form-->
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@user, :html => {class: "form-horizontal",role: "form"}) do |x| %>
		
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= x.label :username %>
			</div>
				<div class="col-sm-8">
					<%= x.text_field :username, class: "form-control", placeholder: "Enter username", autofocus:true %>
				</div>
		</div>
		
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= x.label :email %>
			</div>
				<div class="col-sm-8">
					<%= x.email_field :email, class: "form-control", placeholder: "Enter email", autofocus: true %>
				</div>
		</div>
		
				<div class="form-group">
			<div class="control-label col-sm-2">
				<%= x.label :password %>
			</div>
				<div class="col-sm-8">
					<%= x.password_field :password, class: "form-control", placeholder: "Enter password", autofocus: true %>
				</div>
		</div>
		
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
<!--If a new user is signing up, show this "Sign up" message else..-->
				<%= x.submit(@user.new_record? ? "I'm ready" : "Update your goal", class: "btn btn-primary btn-lg") %>
			</div>
		</div>
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to 'Cancel request and return to view goals', goals_path %> ]	
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1 align="center">Edit your Goal</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">Everyones' Goals</h1>

<div align="center">
	<%= will_paginate %>
				<% @users.each do |user| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li>
		<!--link goes to that user's showpage-->
						<%= link_to gravatar_for(user), user_path(user) %>
					</li>
					<li class="goal-title">
						<%= link_to user.username, user_path(user) %>
					</li>
					<li>
		<!--display the no. of goals the user has created if the user has any-->
						<small>
							<%= pluralize(user.goals.count, "goal") if user.goals %>
						</small>
					</li>
					<% if logged_in? and current_user.admin? %>
					<li>
					<%= link_to "Delete this user", user_path(user), method: :delete, data:
						{ confirm: "Are you sure you want to delete?" } %>
					</li>
					<% end %>
				</div>
			</div>
		</ul>
		<% end %>
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center">Ready to commit?</h1>

<%= render 'form'%>

app/views/users/show.html.erb
<h1><%= @user.username%>'s Goals</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
<!--Defined gravatar_for method in /helpers/application_helper file-->
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<h4 align="center"><%= @user.username %>'s goals</h4>

<div class="center">
	<%= will_paginate @user_goals %>
</div>
<!--select different instance-->
<%= render 'goals/goal', obj: @user_goals %>
<div class="center">
	<%= will_paginate @user_goals %>
</div>